# SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0
"""Independent executable mathematics for the AgentFEM Native Engine."""

__version__ = "0.7.0a1"

from .contract import (
    CONTRACT_NAME,
    CONTRACT_VERSION,
    KernelRequestError,
    kernel_request_schema,
    kernel_result_schema,
    lower_agentfem_ir,
    lower_agentfem_model,
    run_kernel_request,
)
from .diffusion import (
    CellMaterial,
    DiffusionResult,
    DirichletCondition,
    NeumannCondition,
    SteadyDiffusionProblem,
    solve_steady_diffusion,
)
from .dofs import VectorDofMap
from .dynamics import (
    DynamicCheckpoint,
    LinearDynamicsResult,
    LinearSecondOrderSystem,
    assemble_t3_mass,
    build_t3_linear_dynamics,
    integrate_constrained_linear_dynamics,
    integrate_linear_dynamics,
)
from .elasticity import (
    DisplacementCondition,
    ElasticCellMaterial,
    LinearElasticMaterial,
    LinearElasticProblem,
    LinearElasticResult,
    TractionCondition,
    assemble_linear_elasticity,
    assemble_linear_elasticity_prepared,
    p1_body_force_load,
    p1_boundary_traction_load,
    p1_elastic_stiffness,
    p1_strain_displacement,
    prepare_linear_elasticity_assembly,
    solve_linear_elasticity,
)
from .execution import ExecutionReceipt, execute_plan, explain_execution
from .geometry import AffineTriangleMap
from .interchange import (
    INTERCHANGE_FORMAT,
    NativeInterchangeBundle,
    read_native_bundle,
    write_native_bundle,
)
from .materials import (
    J2MaterialPoint,
    J2Response,
    J2State,
    NeoHookeanMaterial,
    NeoHookeanResponse,
    SmallStrainJ2Material,
)
from .mesh import TriangularMesh, unit_square_triangles, unit_square_two_triangles
from .native import native_kernel_available, native_kernel_identity
from .planning import (
    ExecutionPlan,
    native_capabilities,
    plan_linear_dynamics,
    plan_linear_elasticity,
    plan_linear_elasticity_3d,
    plan_steady_diffusion,
)
from .providers import (
    LinearSolveError,
    NativeSparseProvider,
    NativeSparseSolvePlan,
    NumpyDenseProvider,
    ProviderIdentity,
    ProviderUnavailableError,
    ScipySparseProvider,
)
from .quadrature import TriangleQuadrature, integrate_reference, triangle_rule
from .reference import (
    REFERENCE_TRIANGLE_VERTICES,
    inside_reference_triangle,
    p1_basis,
    p1_basis_gradients,
)
from .results import write_legacy_vtk, write_mechanics_vtk
from .runtime import (
    CancellationToken,
    ExecutionContext,
    NativeExecutionError,
    ProgressEvent,
    ResourceBudget,
    enforce_plan_budget,
)
from .solid import (
    LinearElastic3DProblem,
    LinearElastic3DResult,
    SolidCellMaterial,
    SolidDisplacementCondition,
    SolidElasticMaterial,
    SolidTractionCondition,
    assemble_linear_elasticity_3d,
    assemble_linear_elasticity_3d_prepared,
    prepare_linear_elasticity_3d_assembly,
    select_solid_assembly_mode,
    solve_linear_elasticity_3d,
    t4_body_force_load,
    t4_boundary_traction_load,
    t4_elastic_stiffness,
    t4_geometry,
    t4_strain_displacement,
)
from .sparse import (
    BSRMatrix,
    CGReport,
    CGResult,
    CSRAssemblyPlan,
    CSRConstraintPlan,
    CSRMatrix,
    CSRPattern,
    PreparedPreconditioner,
    conjugate_gradient,
)
from .volume_mesh import TetrahedralMesh, unit_cube_tetrahedra

__all__ = (
    "CONTRACT_NAME",
    "CONTRACT_VERSION",
    "INTERCHANGE_FORMAT",
    "REFERENCE_TRIANGLE_VERTICES",
    "AffineTriangleMap",
    "BSRMatrix",
    "CGReport",
    "CGResult",
    "CSRAssemblyPlan",
    "CSRConstraintPlan",
    "CSRMatrix",
    "CSRPattern",
    "CancellationToken",
    "CellMaterial",
    "DiffusionResult",
    "DirichletCondition",
    "DisplacementCondition",
    "DynamicCheckpoint",
    "ElasticCellMaterial",
    "ExecutionContext",
    "ExecutionPlan",
    "ExecutionReceipt",
    "J2MaterialPoint",
    "J2Response",
    "J2State",
    "KernelRequestError",
    "LinearDynamicsResult",
    "LinearElastic3DProblem",
    "LinearElastic3DResult",
    "LinearElasticMaterial",
    "LinearElasticProblem",
    "LinearElasticResult",
    "LinearSecondOrderSystem",
    "LinearSolveError",
    "NativeExecutionError",
    "NativeInterchangeBundle",
    "NativeSparseProvider",
    "NativeSparseSolvePlan",
    "NeoHookeanMaterial",
    "NeoHookeanResponse",
    "NeumannCondition",
    "NumpyDenseProvider",
    "PreparedPreconditioner",
    "ProgressEvent",
    "ProviderIdentity",
    "ProviderUnavailableError",
    "ResourceBudget",
    "ScipySparseProvider",
    "SmallStrainJ2Material",
    "SolidCellMaterial",
    "SolidDisplacementCondition",
    "SolidElasticMaterial",
    "SolidTractionCondition",
    "SteadyDiffusionProblem",
    "TetrahedralMesh",
    "TractionCondition",
    "TriangleQuadrature",
    "TriangularMesh",
    "VectorDofMap",
    "assemble_linear_elasticity",
    "assemble_linear_elasticity_3d",
    "assemble_linear_elasticity_3d_prepared",
    "assemble_linear_elasticity_prepared",
    "assemble_t3_mass",
    "build_t3_linear_dynamics",
    "conjugate_gradient",
    "enforce_plan_budget",
    "execute_plan",
    "explain_execution",
    "inside_reference_triangle",
    "integrate_constrained_linear_dynamics",
    "integrate_linear_dynamics",
    "integrate_reference",
    "kernel_request_schema",
    "kernel_result_schema",
    "lower_agentfem_ir",
    "lower_agentfem_model",
    "native_capabilities",
    "native_kernel_available",
    "native_kernel_identity",
    "p1_basis",
    "p1_basis_gradients",
    "p1_body_force_load",
    "p1_boundary_traction_load",
    "p1_elastic_stiffness",
    "p1_strain_displacement",
    "plan_linear_dynamics",
    "plan_linear_elasticity",
    "plan_linear_elasticity_3d",
    "plan_steady_diffusion",
    "prepare_linear_elasticity_3d_assembly",
    "prepare_linear_elasticity_assembly",
    "read_native_bundle",
    "run_kernel_request",
    "select_solid_assembly_mode",
    "solve_linear_elasticity",
    "solve_linear_elasticity_3d",
    "solve_steady_diffusion",
    "t4_body_force_load",
    "t4_boundary_traction_load",
    "t4_elastic_stiffness",
    "t4_geometry",
    "t4_strain_displacement",
    "triangle_rule",
    "unit_cube_tetrahedra",
    "unit_square_triangles",
    "unit_square_two_triangles",
    "write_legacy_vtk",
    "write_mechanics_vtk",
    "write_native_bundle",
)
